environments:
  dev:
    values:
      - version: 0.0.1
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml
  staging:
    values:
      - version: 0.0.1
        addRedirect: True
        enablePermanentRedirect: True
        oldDomain: meet-staging.beta.numerique.gouv.fr
        newDomain: visio-staging.beta.numerique.gouv.fr
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml
  production:
    values:
      - version: 0.0.1
        addRedirect: True
        enablePermanentRedirect: True
        oldDomain: meet.numerique.gouv.fr
        newDomain: visio.numerique.gouv.fr
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

repositories:
- name: bitnami
  url: registry-1.docker.io/bitnamicharts
  oci: true
- name: livekit
  url: https://helm.livekit.io

releases:
  - name: postgres
    installed: {{ eq .Environment.Name "dev" | toYaml }}
    namespace: {{ .Namespace }}
    chart: bitnami/postgresql
    version: 13.1.5
    values:
      - auth:
          username: dinum
          password: pass
          database: meet
      - tls:
          enabled: true
          autoGenerated: true

  - name: minio
    installed: {{ eq .Environment.Name "dev" | toYaml }}
    namespace: {{ .Namespace }}
    chart: bitnami/minio
    version: 12.10.10
    values: 
      - auth:
          rootUser: meet
          rootPassword: password
      - provisioning:
          enabled: true
          buckets:
            - name: meet-media-storage

  - name: redis
    installed: {{ eq .Environment.Name "dev" | toYaml }}
    namespace: {{ .Namespace }}
    chart: bitnami/redis
    version: 18.19.2
    values:
      - auth:
          password: pass
        architecture: standalone

  - name: extra
    installed: {{ ne .Environment.Name "dev" | toYaml }}
    namespace: {{ .Namespace }}
    chart: ./extra
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml
    values:
    - env.d/{{ .Environment.Name }}/values.meet.yaml.gotmpl
    - addRedirect: {{ .Values | get "addRedirect" "False" }}
      enablePermanentRedirect: {{ .Values | get "enablePermanentRedirect" "False"}}
      oldDomain: {{ .Values | get "oldDomain" "demo.com" }}
      newDomain: {{ .Values | get "newDomain" "demo.com" }}

  - name: meet
    version: {{ .Values.version }}
    namespace: {{ .Namespace }}
    chart: ./meet
    values:
      - env.d/{{ .Environment.Name }}/values.meet.yaml.gotmpl
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

  - name: livekit
    installed: {{ eq .Environment.Name "dev" | toYaml }}
    namespace: {{ .Namespace }}
    chart: livekit/livekit-server
    values:
      - env.d/{{ .Environment.Name }}/values.livekit.yaml.gotmpl
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml
