replicaCount: 1
terminationGracePeriodSeconds: 18000

livekit:
  keys:
      devkey: secret
  log_level: debug
  rtc:
    use_external_ip: false
    port_range_start: 50000
    port_range_end: 60000
    tcp_port: 7881
  redis:
    address: redis-master:6379
    password: pass
  turn:
    enabled: true
    udp_port: 443
    domain: livekit.127.0.0.1.nip.io
    loadBalancerAnnotations: {}


loadBalancer:
  type: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - hosts:
        - livekit.127.0.0.1.nip.io
      secretName: livekit-dinum-cert

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

nodeSelector: {}
resources: {}
