apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: "5m"
  target:
    name: backend
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
{{- range .Values.secrets }}
        {{ .podVariable }}: |-
          {{`{{`}} {{ print "." .name }} {{`}}`}}
{{- end }}
  data:
{{- range .Values.secrets }}
    - secretKey: {{ .name }}
      sourceRef:
        storeRef:
          name: {{ .clusterSecretStore }}
          kind: ClusterSecretStore
      remoteRef:
        key: {{ .itemId }}
        property: {{ .field }}
{{- end }}
