{{ if .Values.addRedirect }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{ if .Values.enablePermanentRedirect }}
    nginx.ingress.kubernetes.io/permanent-redirect: "https://{{ .Values.newDomain }}$request_uri"
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
    {{ end }}
  name: temporary-redirect
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.oldDomain }}
    http:
      paths:
      - backend:
          service:
            name: meet-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: meet-backend
            port:
              number: 80
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.oldDomain }}
    secretName: transitional-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: transitional-tls
  namespace: {{ .Release.Namespace | quote }}
spec:
  dnsNames:
  - {{ .Values.newDomain }}
  - {{ .Values.oldDomain }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ index .Values.ingress.annotations "cert-manager.io/cluster-issuer" }}
  secretName: transitional-tls
  usages:
  - digital signature
  - key encipherment
{{ end }}
