apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: {{ .Release.Namespace | quote }}
stringData:
  DJANGO_SUPERUSER_EMAIL: {{ .Values.djangoSuperUserEmail }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.djangoSuperUserPass }}
  DJANGO_SECRET_KEY: {{ .Values.djangoSecretKey }}
  OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret }}
  LIVEKIT_API_SECRET: {{ .Values.livekitApi.secret }}
  LIVEKIT_API_KEY: {{ .Values.livekitApi.key }}
{{- if .Values.workerSecret }}
  WORKER_SECRET: {{ .Values.workerSecret }}
{{- end }}
