# Generated by Django 5.1.4 on 2025-01-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_resourceaccess_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pin_code',
            field=models.CharField(blank=True, help_text="Unique n-digit code that identifies this room. Automatically generated on creation. Displayed with '#' suffix.", max_length=100, null=True, unique=True, verbose_name='Room PIN code'),
        ),
    ]
